multi update myecho loading

diff --git a/geolocduck b/geolocduck
--- a/geolocduck
+++ b/geolocduck
@@ -24,8 +24,20 @@ while (( $# )); do
 done
 
 
-# Source colors and myecho functions if available
-type _BLU >/dev/null 2>&1 || . /etc/profile.d/01-myecho-colors.sh >/dev/null 2>&1
+# Load myecho for nicer output
+if ! type _MYECHO >/dev/null 2>&1; then
+  if [ -f "/etc/profile.d/01-myecho-colors.sh" ]; then
+    source /etc/profile.d/01-myecho-colors.sh >/dev/null 2>&1
+  elif [ -f "$HOME/01-myecho-colors.sh" ]; then
+    source "$HOME/01-myecho-colors.sh" >/dev/null 2>&1
+  else
+    echo "Nice Output - Install 'myecho' function (in homedir: 01-myecho-colors.sh)"
+    cd "$HOME"
+    curl -s -LO https://raw.githubusercontent.com/zephxs/bash/master/functions/01-myecho-colors.sh
+    head -20 01-myecho-colors.sh |grep -q "^_MYECHO () {" && echo "myecho installed!" || { echo "myecho install failed, exit.."; exit 1; }
+    source "$HOME/01-myecho-colors.sh" >/dev/null 2>&1
+  fi
+fi
 
 ### Main
 # Query duckduckgo.com for "ip address" terms
