multi update myecho loading

diff --git a/musictag b/musictag
--- a/musictag
+++ b/musictag
@@ -4,8 +4,20 @@
 ### v0.2 - var rewrite for lead/trail spaces
 ### v0.1 - first rev + renaming
 
-# nice output
-type _BLU >/dev/null 2>&1 || . ${PREFIX}/etc/profile.d/01-myecho-colors.sh
+# Load myecho for nicer output
+if ! type _MYECHO >/dev/null 2>&1; then
+  if [ -f "/etc/profile.d/01-myecho-colors.sh" ]; then
+    source /etc/profile.d/01-myecho-colors.sh >/dev/null 2>&1
+  elif [ -f "$HOME/01-myecho-colors.sh" ]; then
+    source "$HOME/01-myecho-colors.sh" >/dev/null 2>&1
+  else
+    echo "Nice Output - Install 'myecho' function (in homedir: 01-myecho-colors.sh)"
+    cd "$HOME"
+    curl -s -LO https://raw.githubusercontent.com/zephxs/bash/master/functions/01-myecho-colors.sh
+    head -20 01-myecho-colors.sh |grep -q "^_MYECHO () {" && echo "myecho installed!" || { echo "myecho install failed, exit.."; exit 1; }
+    source "$HOME/01-myecho-colors.sh" >/dev/null 2>&1
+  fi
+fi
 
 # usage
 [ "$1" = '-h' -o "$1" = '--help' ] && _MYECHO -p "Usage:
diff --git a/wg-genconf b/wg-genconf
--- a/wg-genconf
+++ b/wg-genconf
@@ -40,11 +40,20 @@ _GENSERVER='false'	# Generate Server Config File
 _GENCLIENT='false'	# Generate Client Config File
 _QUIET='false'		# Verbose Mode
 
-
-if ! type -t _MYECHO &>/dev/null;then
-  . /etc/profile.d/01-myecho-colors.sh
+# Load myecho for nicer output
+if ! type _MYECHO >/dev/null 2>&1; then
+  if [ -f "/etc/profile.d/01-myecho-colors.sh" ]; then
+    source /etc/profile.d/01-myecho-colors.sh >/dev/null 2>&1
+  elif [ -f "$HOME/01-myecho-colors.sh" ]; then
+    source "$HOME/01-myecho-colors.sh" >/dev/null 2>&1
+  else
+    echo "Nice Output - Install 'myecho' function (in homedir: 01-myecho-colors.sh)"
+    cd "$HOME"
+    curl -s -LO https://raw.githubusercontent.com/zephxs/bash/master/functions/01-myecho-colors.sh
+    head -20 01-myecho-colors.sh |grep -q "^_MYECHO () {" && echo "myecho installed!" || { echo "myecho install failed, exit.."; exit 1; }
+    source "$HOME/01-myecho-colors.sh" >/dev/null 2>&1
+  fi
 fi
-! type -t _MYECHO &>/dev/null && echo "Profile Output Scripts not found.. Exit" && exit 1
 
 _USAGE () {
 _MYECHO -l
