termux-url-opener - add checks

diff --git a/termux-url-opener b/termux-url-opener
--- a/termux-url-opener
+++ b/termux-url-opener
@@ -9,14 +9,17 @@
 _VIDEOS='/data/data/com.termux/files/home/storage/shared/youtube/%(title)s.%(ext)s'
 _ABOOKS='/data/data/com.termux/files/home/storage/shared/Music/6-audiobooks/%(title)s.%(ext)s'
 _ZIKS='/data/data/com.termux/files/home/storage/shared/Music/5-Newz/%(title)s.%(ext)s'
+[ -d "$_VIDEOS" -o -d "$_ABOOKS" -o -d "$_ZIKS" ] || { echo "# Destination Folders not found, exit" && exit; } 
 
 ### AUTO INSTALLER
+if type pkg >/dev/null ; then
 # required pip for easy install and update
 type pip >/dev/null || ( echo "... Installing pip" && pkg install python3; )
 # install yt-dlp and update if bin older than 15 days
 find $(type -P yt-dlp) -mtime +15 -exec python3 -m pip install -U yt-dlp \; || python3 -m pip install -U yt-dlp
 # install screen for backgrounding - can be removed with occurences if not needed
 type screen >/dev/null || ( echo "... Installing screen" && pkg install screen; )
+fi
 
 ### FUNCTIONS
 _MYECHO () { 
