android-scriptmod - add quiet mode

diff --git a/android/android-scriptmod b/android/android-scriptmod
--- a/android/android-scriptmod
+++ b/android/android-scriptmod
@@ -1,65 +1,80 @@
 #!/bin/bash
 ### Termux / Android Chroot Bash script modder
-### v0.2 - $TMPDIR support added 
+### v0.4 - Quiet mode added
+### v0.3 - $TMPDIR support added
 # mod '/etc' to '${_ETC}' and '/tmp' to '$TMPDIR' occurences in script for Android
 
 # VARS
 _ETCREPLACE="\${_ETC}"
 _TMPREPLACE="\${TMPDIR}"
+_QUIET=false
+_VERS=$(awk '/### v/ {print $0; exit}' $basename $0 |awk '{print $2}')
 
-[ "$1" = "-h" ] || [ "$1" = "--help" ] && echo "# Usage: android-scriptmod <script>" && exit 0
-[ "$1" = "-v" ] || [ "$1" = "--version" ] && echo "# android-scriptmod v0.2" && exit 0
-[ -z "$1" ] && echo "# Usage: android-scriptmod <script>" && exit 1
-[ ! -f "$1" ] && echo "# File not found: $1" && exit 1
+# Define usage function
+usage() {
+  echo "Usage: $0 [-h|--help] [-v|--version] [-q|--quiet] <script>"
+  echo "  -h, --help    Show this help message"
+  echo "  -v, --version Show the version number"
+  echo "  -q, --quiet   Run in quiet mode"
+  echo "  <script>      The script to modify"
+}
 
-_SCRIPT=$1
-echo "##############################################"
-echo "### Termux / Android Chroot Bash script modder"
-echo
-if grep -q '#!/bin/bash' ${_SCRIPT}; then
-  echo "# ${_SCRIPT} is a bash script [OK]"
-  if grep -q '/etc' ${_SCRIPT}; then
-    echo "# Script contains '/etc' occurences:"
-    grep -E '/etc' ${_SCRIPT}
-    sed -i "s/\/etc/${_ETCREPLACE}/g" ${_SCRIPT}
-    echo "# Script '/etc' occurences modded to '\${_ETC}' [OK]"
-    grep $_ETCREPLACE ${_SCRIPT}
-    echo
-      else
-    echo "# Script does not contain '/etc' occurences"
-  fi
-  if grep -q '/tmp' ${_SCRIPT}; then
-    echo "# Script contains '/tmp' occurences:"
-    grep -E '/tmp' ${_SCRIPT}
-    sed -i "s/\/tmp/${_TMPREPLACE}/g" ${_SCRIPT}
-    echo "# Script '/tmp' occurences modded to '\${TMPDIR}' [OK]"
-    grep $_TMPREPLACE ${_SCRIPT}
-    echo
-  else
-    echo "# Script does not contain '/tmp' occurences"
-  fi
-elif grep -q '#!/usr/bin/env bash' ${_SCRIPT}; then
-  echo "# $_SCRIPT is a bash script [OK]"
-  if grep -q '/etc' ${_SCRIPT}; then
-    echo "# Script contains '/etc' occurences:"
-    grep -E '/etc' ${_SCRIPT}
-    sed -i "s/\/etc/${_ETCREPLACE}/g" ${_SCRIPT}
-    echo "# Script '/etc' occurences modded to '\${_ETC}' [OK]"
-    grep $_ETCREPLACE ${_SCRIPT}
-    echo
-  else
-    echo "# Script does not contain '/etc' occurences"
-  fi
-  if grep -q '/tmp' ${_SCRIPT}; then
-    echo "# Script contains '/tmp' occurences"
-    grep -E '/tmp' ${_SCRIPT}
-    sed -i "s/\/tmp/${_TMPREPLACE}/g" ${_SCRIPT}
-    echo "# Script '/tmp' occurences modded to '\${TMPDIR}' [OK]"
-    grep $_TMPREPLACE ${_SCRIPT}
-    echo
-  else
-    echo "Script does not contain '/tmp' occurences"
-  fi
-else
-  echo "Script is not a bash script"
+# Parse command-line options
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h|--help)
+      usage
+      exit 0
+      ;;
+    -v|--version)
+      echo "$_VERS"
+      exit 0
+      ;;
+    -q|--quiet)
+      _QUIET=true
+      shift
+      ;;
+    *)
+      SCRIPT="$1"
+      shift
+      ;;
+  esac
+done
+
+# Check for missing script argument
+if [ -z "$SCRIPT" ]; then
+  echo "Error: missing script argument"
+  usage
+  exit 1
 fi
+
+# Check for non-existent script
+if [ ! -f "$SCRIPT" ]; then
+  echo "Error: file not found: $SCRIPT"
+  exit 1
+fi
+
+# Modify script
+if grep -q '#!/bin/bash' "$SCRIPT" || grep -q '#!/usr/bin/env bash' "$SCRIPT"; then
+  if grep -q '/etc' "$SCRIPT"; then
+      [ "$_QUIET" = false ] && echo "# Modifying '/etc' occurences in $SCRIPT..." && grep -E '/etc' "$SCRIPT"
+    sed -i "s/\/etc/${_ETCREPLACE}/g" "$SCRIPT"
+      [ "$_QUIET" = false ] && echo "# '/etc' occurences modded to '\${_ETC}' [OK]" && grep "$_ETCREPLACE" "$SCRIPT"
+  else
+      [ "$_QUIET" = false ] && echo "# No '/etc' occurences found in $SCRIPT"
+  fi
+
+  if grep -q '/tmp' "$SCRIPT"; then
+      [ "$_QUIET" = false ] && echo "# Modifying '/tmp' occurences in $SCRIPT..." && grep -E '/tmp' "$SCRIPT"
+    sed -i "s/\/tmp/${_TMPREPLACE}/g" "$SCRIPT"
+      [ "$_QUIET" = false ] && echo "# '/tmp' occurences modded to '\${TMPDIR}' [OK]" && grep "$_TMPREPLACE" "$SCRIPT"
+  else
+      [ "$_QUIET" = false ] && echo "# No '/tmp' occurences found in $SCRIPT"
+  fi
+
+    [ "$_QUIET" = false ] && echo "### Modifications complete."
+else
+  echo "Error: $SCRIPT is not a bash script"
+  exit 1
+fi
+
