IPSet-Nginx-BanScript - update

diff --git a/ipset/IPSet-Nginx-BanScript b/ipset/IPSet-Nginx-BanScript
--- a/ipset/IPSet-Nginx-BanScript
+++ b/ipset/IPSet-Nginx-BanScript
@@ -7,9 +7,9 @@ echo "##################################"
 
 XTMP=$(mktemp /root/blacklist/nginx-tmp1-XXX)
 XTMP2=$(mktemp /root/blacklist/nginx-tmp2-XXX)
-XLIST='/root/blacklist/nginx-ban-list'
-XBAN='/root/blacklist/nginx-ban-ips'
-YOURIPHERE="PUT Your IPs here Space separated"
+XLIST='/root/blacklist/logs/nginx-ban-list'
+XBAN='/root/blacklist/logs/nginx-ban-ips'
+YOURIPHERE="" #PUT Your IPs here Space separated
 
 # backup and cleanup existing IP lists
 [ -f "$XLIST" ] && cp $XLIST{,-$(date "+%Y-%m-%d")}
@@ -22,32 +22,30 @@ echo "# Search for scanner in nginx logs..."
 cat /var/log/nginx/access.log|egrep -i 'masscan|CensysInspect|status|bot|nessus|netcraft|admin'|grep -v "127.0.0.1"|grep -oE "\b([0-9]{1,3}.){3}[0-9]{1,3}\b" >$XTMP
 zcat /var/log/nginx/access.log*.gz|egrep -i 'masscan|CensysInspect|status|bot|nessus|netcraft|admin'|grep -v "127.0.0.1"|grep -oE "\b([0-9]{1,3}.){3}[0-9]{1,3}\b" >>$XTMP
 echo
-sed -i "/^3/d" $XTMP 
-sed -i "/^200 /d" $XTMP 
-sed -i "/^400 /d" $XTMP 
-sed -i "/^404 /d" $XTMP 
-sed -i "/^2010/d" $XTMP 
-sed -i "/^2019/d" $XTMP 
-sed -i "/^2020/d" $XTMP 
-sort $XTMP | uniq -u > $XTMP2 && rm -f $XTMP
+sed -i "/^3/d; /^200 /d; /^400 /d; /^404 /d; /^2010/d; /^2019/d; /^2020/d; /^2021/d" $XTMP
+sort -u $XTMP > $XTMP2 && rm -f $XTMP
 
 echo "# Check for IP address in detected logs..."
-#sort -u < $XTMP2 | egrep "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(/[0-9]{1,2})?$" > $XBAN
-for ip in $(cat "$XTMP2"); do
-if [ ! $(echo "$ip" | tr '.' ' ' | wc -w) -ne 4 ] ; then
-echo "$ip" >> $XLIST
-fi
+for _IP in $(cat "$XTMP2"); do
+  if [ ! $(echo "$_IP" | tr '.' ' ' | wc -w) -ne 4 ] ; then
+    echo "$_IP" >> $XLIST
+  fi
 done
-rm -f $XTMP2 && sort $XLIST | uniq -u > $XBAN
+rm -f $XTMP2 && sort -u $XLIST > $XBAN
 echo
 echo "# ... $(cat $XBAN|wc -l) IPs Found"
 echo
 echo "# Check and add if not already Blacklisted... (need blacklist-check script in path)"
-if ! command -v blacklist-check &> /dev/null; then echo "blacklist-check could not be found"
+if ! command -v blacklist-check &> /dev/null; then 
+  echo "blacklist-check could not be found"
 else
-for i in $(cat "$XBAN"); do 
-blacklist-check $i > /dev/null 2>&1 || ipset add manual-blacklist $i
-done
+  for i in $(cat "$XBAN"); do 
+  if ! blacklist-check $i > /dev/null 2>&1; then
+    ipset add manual-blacklist $i
+    #Telegram alert
+    telegram-send "[LTS] NGinX Sniffer # $i got blacklisted"
+  fi
+  done
 fi
 echo
 echo "# Check and protect $YOURIPHERE 'nomatch' IP"
